---
- block:
    - name: Wait for Under Replicated Partitions Metric to return 200
      uri:
        url: "{{ kafka_broker_jolokia_urp_url }}"
        validate_certs: false
        # If no auth on jolokia, adding user/pass is redundant but still functional
        force_basic_auth: true
        url_username: "{{kafka_broker_jolokia_user}}"
        url_password: "{{kafka_broker_jolokia_password}}"
        return_content: true
        status_code: 200
      register: result
      until: result.status == 200
      retries: 600
      delay: 5

    - name: Wait for Under Replicated Partitions Metric to return Data
      uri:
        url: "{{ kafka_broker_jolokia_urp_url }}"
        validate_certs: false
        return_content: true
        # If no auth on jolokia, adding user/pass is redundant but still functional
        force_basic_auth: true
        url_username: "{{kafka_broker_jolokia_user}}"
        url_password: "{{kafka_broker_jolokia_password}}"
        status_code: 200
      register: result
      until: result['json']['value'] is defined
      retries: 600
      delay: 5

    # curl localhost:7771/jolokia/read/kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions
    # {"request":{"mbean":"kafka.server:name=UnderReplicatedPartitions,type=ReplicaManager","type":"read"},"value":{"Value":0},"timestamp":1565819946,"status":200}
    - name: Wait for Under Replicated Partitions Metric to equal Zero
      uri:
        url: "{{ kafka_broker_jolokia_urp_url }}"
        validate_certs: false
        return_content: true
        # If no auth on jolokia, adding user/pass is redundant but still functional
        force_basic_auth: true
        url_username: "{{kafka_broker_jolokia_user}}"
        url_password: "{{kafka_broker_jolokia_password}}"
        status_code: 200
      register: result
      until: result['json']['value']['Value'] == 0
      retries: 600
      delay: 5
  when: not ansible_check_mode
