FROM {{ item.image }}

RUN yum -y install java-11-openjdk \
      rsync \
      openssl

RUN mkdir /opt/confluent && \
    curl -o /opt/confluent/confluent-6.2.2.tar.gz https://staging-confluent-packages.s3.us-west-2.amazonaws.com/archive/6.2/confluent-6.2.2.tar.gz && \
    tar xzf /opt/confluent/confluent-6.2.2.tar.gz -C /opt/confluent/ && \
    rm -rf /opt/confluent/confluent-6.2.2.tar.gz
