skip_properties:
  - bootstrap.servers
  - confluent.controlcenter.connect.connect-cluster.cluster
  - confluent.controlcenter.ksql.ksql.advertised.url
  - confluent.controlcenter.ksql.ksql.url
  - confluent.controlcenter.schema.registry.url
  - confluent.controlcenter.streams.cprest.url
  - confluent.controlcenter.streams.num.stream.threads
  - confluent.controlcenter.streams.sasl.jaas.config
  - confluent.controlcenter.streams.sasl.mechanism
  - confluent.controlcenter.streams.security.protocol
  - confluent.monitoring.interceptor.sasl.mechanism
  - confluent.monitoring.interceptor.security.protocol
  - confluent.monitoring.interceptor.sasl.jaas.config
  - confluent.controlcenter.schema.registry.schema.registry.ssl.truststore.location
  - confluent.controlcenter.schema.registry.schema.registry.ssl.truststore.password
  - confluent.controlcenter.schema.registry.schema.registry.ssl.keystore.location
  - confluent.controlcenter.schema.registry.schema.registry.ssl.keystore.password
  - confluent.controlcenter.schema.registry.schema.registry.ssl.key.password
  - confluent.controlcenter.connect.connect-cluster.ssl.key.password
  - confluent.controlcenter.connect.connect-cluster.ssl.keystore.location
  - confluent.controlcenter.connect.connect-cluster.ssl.keystore.password
  - confluent.controlcenter.connect.connect-cluster.ssl.truststore.location
  - confluent.controlcenter.connect.connect-cluster.ssl.truststore.password
  - confluent.controlcenter.ksql.ksql.ssl.key.password
  - confluent.controlcenter.ksql.ksql.ssl.keystore.location
  - confluent.controlcenter.ksql.ksql.ssl.keystore.password
  - confluent.controlcenter.ksql.ksql.ssl.truststore.location
  - confluent.controlcenter.ksql.ksql.ssl.truststore.password
  - confluent.controlcenter.streams.ssl.truststore.location
  - confluent.controlcenter.streams.ssl.truststore.password
  - confluent.controlcenter.streams.ssl.key.password
  - confluent.controlcenter.streams.ssl.keystore.location
  - confluent.controlcenter.streams.ssl.keystore.password
  - confluent.monitoring.interceptor.ssl.truststore.location
  - confluent.monitoring.interceptor.ssl.truststore.password
  - confluent.monitoring.interceptor.ssl.key.password
  - confluent.monitoring.interceptor.ssl.keystore.location
  - confluent.monitoring.interceptor.ssl.keystore.password
  - confluent.controlcenter.schema.registry.basic.auth.credentials.source
  - confluent.controlcenter.rest.authentication.realm
  - confluent.controlcenter.auth.restricted.roles
  - confluent.controlcenter.auth.session.expiration.ms
  - confluent.metadata.ssl.truststore.location
  - confluent.metadata.ssl.truststore.password
  - confluent.metadata.ssl.endpoint.identification.algorithm
  - confluent.metadata.http.auth.credentials.provider