skip_properties:
  - bootstrap.servers
  - confluent.controlcenter.connect.connect-cluster.cluster
  - confluent.controlcenter.ksql.ksql.advertised.url
  - confluent.controlcenter.ksql.ksql.url
  - confluent.controlcenter.schema.registry.url
  - confluent.controlcenter.streams.cprest.url
  - confluent.controlcenter.streams.num.stream.threads
  - confluent.controlcenter.streams.sasl.jaas.config
  - confluent.controlcenter.streams.sasl.mechanism
  - confluent.controlcenter.streams.security.protocol
  - confluent.monitoring.interceptor.sasl.mechanism
  - confluent.monitoring.interceptor.security.protocol
  - confluent.monitoring.interceptor.sasl.jaas.config
