skip_properties:
# Written by Ansible
  - bootstrap.servers
  - config.providers.secret.param.kafkastore.sasl.jaas.config
  - config.providers.secret.param.kafkastore.sasl.mechanism
  - config.providers.secret.param.kafkastore.security.protocol
  - confluent.license.topic
  - consumer.bootstrap.servers
  - consumer.confluent.monitoring.interceptor.bootstrap.servers
  - consumer.confluent.monitoring.interceptor.sasl.jaas.config
  - consumer.confluent.monitoring.interceptor.sasl.mechanism
  - consumer.confluent.monitoring.interceptor.security.protocol
  - consumer.interceptor.classes
  - consumer.sasl.jaas.config
  - consumer.sasl.mechanism
  - consumer.security.protocol
  - internal.key.converter
  - internal.key.converter.schemas.enable
  - internal.value.converter
  - internal.value.converter.schemas.enable
  - key.converter
  - key.converter.schema.registry.url
  - offset.flush.interval.ms
  - offset.storage.replication.factor
  - offset.storage.topic
  - producer.bootstrap.servers
  - producer.confluent.monitoring.interceptor.bootstrap.servers
  - producer.confluent.monitoring.interceptor.sasl.jaas.config
  - producer.confluent.monitoring.interceptor.sasl.mechanism
  - producer.confluent.monitoring.interceptor.security.protocol
  - producer.interceptor.classes
  - producer.sasl.jaas.config
  - producer.sasl.mechanism
  - producer.security.protocol
  - rest.advertised.host.name
  - rest.port
  - sasl.jaas.config
  - sasl.mechanism
  - security.protocol
  - status.storage.replication.factor
  - status.storage.topic
  - value.converter
  - value.converter.schema.registry.url
