skip_properties:
  - bootstrap.servers
  - client.confluent.monitoring.interceptor.bootstrap.servers
  - client.confluent.monitoring.interceptor.sasl.jaas.config
  - client.confluent.monitoring.interceptor.sasl.mechanism
  - client.confluent.monitoring.interceptor.security.protocol
  - client.sasl.jaas.config
  - client.sasl.mechanism
  - client.security.protocol
  - confluent.license.topic
  - confluent.monitoring.interceptor.topic=_confluent-monitoring
  - consumer.interceptor.classes
  - producer.interceptor.classes
  - host.name
  - id
  - schema.registry.url
  - schema.registry.ssl.key.password
  - schema.registry.ssl.keystore.location
  - schema.registry.ssl.keystore.password
  - schema.registry.ssl.truststore.location
  - schema.registry.ssl.truststore.password
