skip_properties:
  - advertised.listeners
  - num.partitions
  - listener.security.protocol.map
  - kafka.rest.client.sasl.jaas.config
  - sasl.mechanism.inter.broker.protocol
  - kafka.rest.client.security.protocol
  - kafka.rest.client.sasl.mechanism
  - group.initial.rebalance.delay.ms
  - confluent.ansible.managed
  - confluent.support.customer.id
  - num.network.threads
  - confluent.support.metrics.enable
  - log.retention.check.interval.ms
  - log.retention.hours
  - log.segment.bytes
  - metric.reporters
  - num.io.threads
  - zookeeper.connection.timeout.ms
  - socket.receive.buffer.bytes
  - socket.request.max.bytes
  - socket.send.buffer.bytes
  - confluent.security.event.logger.exporter.kafka.topic.replicas
  - zookeeper.connect
  - num.recovery.threads.per.data.dir
  - offsets.topic.replication.factor
  - transaction.state.log.min.isr
  - transaction.state.log.replication.factor
  - sasl.enabled.mechanisms
  - confluent.metrics.reporter.topic.replicas
  - confluent.metrics.reporter.sasl.jaas.config
  - confluent.metrics.reporter.sasl.mechanism
  - confluent.metrics.reporter.security.protocol
