skip_properties:
  - advertised.listeners
  - num.partitions
  - listener.security.protocol.map
  - kafka.rest.client.sasl.jaas.config
  - sasl.mechanism.inter.broker.protocol
  - kafka.rest.client.security.protocol
  - kafka.rest.client.sasl.mechanism
  - group.initial.rebalance.delay.ms
  - confluent.ansible.managed
  - confluent.support.customer.id
  - num.network.threads
  - confluent.support.metrics.enable
  - log.retention.check.interval.ms
  - log.retention.hours
  - log.segment.bytes
  - metric.reporters
  - num.io.threads
  - zookeeper.connection.timeout.ms
  - socket.receive.buffer.bytes
  - socket.request.max.bytes
  - socket.send.buffer.bytes
  - confluent.security.event.logger.exporter.kafka.topic.replicas
  - zookeeper.connect
  - num.recovery.threads.per.data.dir
  - offsets.topic.replication.factor
  - transaction.state.log.min.isr
  - transaction.state.log.replication.factor
  - sasl.enabled.mechanisms
  - confluent.metrics.reporter.topic.replicas
  - confluent.metrics.reporter.sasl.jaas.config
  - confluent.metrics.reporter.sasl.mechanism
  - confluent.metrics.reporter.security.protocol
  - zookeeper.ssl.client.enable
  - zookeeper.clientCnxnSocket
  - security.providers
  - ssl.keymanager.algorithm
  - ssl.trustmanager.algorithm
  - ssl.keystore.type
  - ssl.truststore.type
  - confluent.ssl.truststore.location
  - confluent.ssl.truststore.password
  - confluent.ssl.keystore.location
  - confluent.ssl.keystore.password
  - confluent.ssl.key.password
  - listener.name.broker.ssl.key.password 
  - listener.name.broker.ssl.keystore.location  
  - listener.name.broker.ssl.keystore.password  
  - listener.name.broker.ssl.truststore.location  
  - listener.name.broker.ssl.truststore.password  
  - listener.name.internal.ssl.key.password 
  - listener.name.internal.ssl.keystore.location  
  - listener.name.internal.ssl.keystore.password  
  - listener.name.internal.ssl.truststore.location  
  - listener.name.internal.ssl.truststore.password  
  - confluent.ssl.keymanager.algorithm
  - confluent.ssl.trustmanager.algorithm
  - confluent.ssl.keystore.type
  - confluent.ssl.truststore.type
  - confluent.http.server.ssl.keystore.location
  - confluent.http.server.ssl.keystore.password
  - confluent.http.server.ssl.key.password
  - confluent.http.server.ssl.truststore.location
  - confluent.http.server.ssl.truststore.password
  - confluent.http.server.ssl.keymanager.algorithm
  - confluent.http.server.ssl.trustmanager.algorithm
  - confluent.http.server.ssl.keystore.type
  - confluent.http.server.ssl.truststore.type
  - kafka.rest.resource.extension.class
  - kafka.rest.confluent.rest.auth.propogate.method
  - kafka.rest.authentication.realm
  - kafka.rest.client.ssl.truststore.location
  - kafka.rest.client.ssl.truststore.password
  - confluent.metrics.reporter.ssl.truststore.location
  - confluent.metrics.reporter.ssl.truststore.password
