skip_properties:
# Written by Ansible
  - confluent.monitoring.interceptor.bootstrap.servers
  - confluent.monitoring.interceptor.sasl.jaas.config
  - confluent.monitoring.interceptor.sasl.mechanism
  - confluent.monitoring.interceptor.security.protocol
  - confluent.monitoring.interceptor.topic
  - consumer.interceptor.classes
  - ksql.schema.registry.url
  - ksql.streams.producer.delivery.timeout.ms
  - ksql.streams.producer.max.block.ms
  - ksql.streams.replication.factor
  - producer.interceptor.classes
  - sasl.jaas.config
  - sasl.mechanism
  - security.protocol
  - bootstrap.servers
  - ksql.streams.num.standby.replicas
  - ksql.schema.registry.ssl.key.password
  - ksql.schema.registry.ssl.keystore.location
  - ksql.schema.registry.ssl.keystore.password
  - ksql.schema.registry.ssl.truststore.location
  - ksql.schema.registry.ssl.truststore.password
  - ksql.schema.registry.basic.auth.credentials.source
  - ksql.schema.registry.basic.auth.user.info
  - authentication.realm
  - confluent.monitoring.interceptor.ssl.key.password
  - confluent.monitoring.interceptor.ssl.keystore.location
  - confluent.monitoring.interceptor.ssl.keystore.password
  - confluent.monitoring.interceptor.ssl.truststore.location
  - confluent.monitoring.interceptor.ssl.truststore.password
