skip_properties:
  - admin.enableServer
  - autopurge.purgeInterval
  - autopurge.snapRetainCount
  - initLimit
  - maxClientCnxns
  - server.1
  - syncLimit
  - serverCnxnFactory
  - authProvider.x509
  - sslQuorum
  - ssl.quorum.keyStore.location
  - ssl.quorum.keyStore.password
  - ssl.quorum.trustStore.location
  - ssl.quorum.trustStore.password
